// Realistic demo data for 9-stage pre-auth workflow (TPA Copilot)

import type { PreAuthWorkflowData, WorkflowStageId } from "./types";

const workflowByPreAuthId: Record<string, PreAuthWorkflowData> = {
  PA001: {
    requestSummary: {
      admissionType: "emergency",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-4521", present: true },
        { label: "Policy document", value: "STAR/HL/2023/456789", present: true },
        { label: "Doctor consultation notes", value: "Chief complaint: chest pain, STEMI", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "I21.9 – Acute MI", present: true },
        { label: "Proposed treatment", value: "Coronary angioplasty with stent", present: true },
        { label: "Estimated cost (rate card)", value: "₹2,85,000", present: true },
        { label: "ECG, Troponin, Lipid profile", value: "Attached", present: true },
        { label: "Past cardiac history", value: "Hypertension, no prior MI", present: true },
      ],
    },
    timeline: [
      {
        id: "t1",
        title: "Case received",
        timestamp: "2025-02-03 09:12",
        status: "done",
        detail: "Emergency pre-auth request submitted by hospital desk.",
      },
      {
        id: "t2",
        title: "Assigned to reviewer",
        timestamp: "2025-02-03 09:20",
        status: "done",
        meta: [{ label: "Assignee", value: "Anita Desai · Senior Claims Analyst" }],
      },
      {
        id: "t3",
        title: "Initial document check",
        timestamp: "2025-02-03 09:35",
        status: "done",
        detail: "Core documents present; consent form missing.",
      },
      {
        id: "t4",
        title: "Additional documents requested",
        timestamp: "2025-02-03 09:50",
        status: "info",
        detail: "Consent form + pre-op investigation reports requested.",
      },
      {
        id: "t5",
        title: "Current status",
        timestamp: "2025-02-03 10:05",
        status: "current",
        detail: "Awaiting hospital response to document query.",
      },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums paid; no lapse." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid until Dec 2025." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Cardiac procedures under plan." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹10L cardiac sub-limit", detail: "₹2.85L well within limit; ₹1.2L used this year." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "24 months since inception; cardiac waiting period satisfied." },
    ],
    coding: {
      icd10: [
        {
          id: "icd1", type: "icd10", code: "I21.9",
          description: "Acute myocardial infarction, unspecified",
          status: "valid",
          clinicalContext: "\"Patient presented with acute chest pain radiating to left arm, elevated troponin (2.4× ULN), ST-elevation in V1–V4 on 12-lead ECG.\" — Consultation notes, p.2",
          diagnosisMatch: "Matches procedure — I21.9 is the standard indication for percutaneous coronary intervention",
          suggestion: "Consider I21.01 (STEMI of anterior wall) for greater specificity if LAD involvement confirmed",
        },
      ],
      cpt: [
        {
          id: "cpt1", type: "cpt", code: "93454",
          description: "Catheter placement in coronary artery for coronary angiography",
          status: "valid",
          clinicalContext: "\"Pre-procedure angiography performed to assess coronary anatomy and degree of stenosis before stent placement.\" — Operative note, p.1",
          diagnosisMatch: "Standard diagnostic step prior to stenting in STEMI protocol",
        },
        {
          id: "cpt2", type: "cpt", code: "92928",
          description: "Percutaneous transcatheter placement of intracoronary stent(s), with coronary angioplasty",
          status: "valid",
          clinicalContext: "\"PTCA with drug-eluting stent placed in LAD; 95% stenosis resolved to <10% post-procedure.\" — Procedure report, p.3",
          diagnosisMatch: "Matches diagnosis — standard treatment for acute MI with significant coronary stenosis (I21.9 → 92928)",
        },
      ],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Standard treatment for STEMI; cashless eligible.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer cardiac policy", finding: "Angioplasty + stent covered for acute MI with supporting ECG/troponin.", status: "met" },
    ],
    medicalNecessityScore: 92,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "I21.9",
        diagnosisDescription: "Acute myocardial infarction, unspecified",
        procedureCode: "92928",
        procedureDescription: "Percutaneous transcatheter placement, stent",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 77,
        aiSummary: "Similar STEMI cases with stenting are commonly approved when ECG/troponin evidence is present.",
        sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/31760641/",
        sourceLabel: "View evidence",
      },
      {
        id: "mni2",
        diagnosisCode: "I21.9",
        diagnosisDescription: "Acute myocardial infarction, unspecified",
        procedureCode: "93454",
        procedureDescription: "Catheter placement, coronary angiography",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 69,
        aiSummary: "Angiography is routinely linked to acute MI workup when cardiac markers and ECG confirm diagnosis.",
        sourceUrl: "https://pubmed.ncbi.nlm.nih.gov/31760641/",
        sourceLabel: "View evidence",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "low", description: "Timeline: symptoms 2 days; admission 1 day – consistent with acute STEMI presentation.", patientClaimsCount: 1 },
      { id: "f2", category: "provider", severity: "none", description: "Hospital in network; no prior fraud flags on record.", providerFraudRate: 0.8 },
    ],
    queries: [
      { id: "q1", question: "Consent form with patient signature not received.", status: "open", dueDate: "2025-02-04" },
      { id: "q2", question: "Pre-operative investigation reports (ECG, Troponin, Lipid) requested.", status: "open", dueDate: "2025-02-04" },
    ],
    p2pRequired: false,
  },
  PA002: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-7832", present: true },
        { label: "Policy document", value: "HDFC/HL/2022/234567", present: true },
        { label: "Doctor consultation notes", value: "Symptomatic gallstones, recurrent pain", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "K80.1 – Gallstones with cholecystitis", present: true },
        { label: "Proposed treatment", value: "Laparoscopic cholecystectomy", present: true },
        { label: "Estimated cost (rate card)", value: "₹1,75,000", present: true },
        { label: "USG abdomen, LFT", value: "Attached", present: true },
        { label: "Past illness records", value: "Nil relevant", present: true },
      ],
    },
    timeline: [
      {
        id: "t1",
        title: "Case received",
        timestamp: "2025-02-02 14:05",
        status: "done",
        detail: "Planned admission pre-auth request submitted.",
      },
      {
        id: "t2",
        title: "Assigned to reviewer",
        timestamp: "2025-02-02 14:22",
        status: "done",
        meta: [{ label: "Assignee", value: "Harsh Vora · Claims Analyst" }],
      },
      {
        id: "t3",
        title: "Documentation complete",
        timestamp: "2025-02-02 14:40",
        status: "done",
        detail: "All IRDAI checklist items verified.",
      },
      {
        id: "t4",
        title: "Eligibility confirmed",
        timestamp: "2025-02-02 15:05",
        status: "done",
        detail: "Coverage limits and waiting periods satisfied.",
      },
      {
        id: "t5",
        title: "Current status",
        timestamp: "2025-02-02 15:12",
        status: "current",
        detail: "Under review for final decision.",
      },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums paid; employee in service (group)." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Request within policy period." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Laparoscopic surgery under general surgery." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹5L annual", detail: "₹1.75L within limit; ₹0.8L utilized this year." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "30-day initial waiting period completed." },
    ],
    coding: {
      icd10: [
        { id: "icd1", type: "icd10", code: "K80.1", description: "Calculus of gallbladder with acute cholecystitis", status: "valid" },
      ],
      cpt: [
        { id: "cpt1", type: "cpt", code: "47562", description: "Laparoscopy, surgical; cholecystectomy", status: "valid" },
      ],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Standard treatment for symptomatic gallstones.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer surgical policy", finding: "Lap chole approved when USG + clinical picture support.", status: "met" },
    ],
    medicalNecessityScore: 88,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "K80.1",
        diagnosisDescription: "Calculus of gallbladder with acute cholecystitis",
        procedureCode: "47562",
        procedureDescription: "Laparoscopy, surgical; cholecystectomy",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 81,
        aiSummary: "Cases with USG-confirmed cholecystitis and laparoscopic cholecystectomy are frequently approved.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK448145/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "none", description: "Documents consistent; no anomalies." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital; no red flags." },
    ],
    queries: [],
    p2pRequired: false,
  },
  PA003: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "Driving license – DL-09-XXXX", present: true },
        { label: "Policy document", value: "ICICI/HL/2023/789012", present: true },
        { label: "Doctor consultation notes", value: "Severe knee OA, failed conservative care", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "M17.11 – Unilateral primary OA, right knee", present: true },
        { label: "Proposed treatment", value: "Total knee replacement", present: true },
        { label: "Estimated cost (rate card)", value: "₹4,20,000 (implant breakup missing)", present: false },
        { label: "Pre-operative X-ray/MRI", value: "Not attached", present: false },
        { label: "Doctor recommendation with stamp", value: "Missing stamp", present: false },
      ],
    },
    timeline: [
      {
        id: "t1",
        title: "Case received",
        timestamp: "2025-02-03 11:18",
        status: "done",
        detail: "Pre-auth request submitted for TKR.",
      },
      {
        id: "t2",
        title: "Assigned to reviewer",
        timestamp: "2025-02-03 11:34",
        status: "done",
        meta: [{ label: "Assignee", value: "Meera Nair · Ortho Desk" }],
      },
      {
        id: "t3",
        title: "Documentation gaps detected",
        timestamp: "2025-02-03 12:02",
        status: "done",
        detail: "Implant cost breakup + imaging + stamped recommendation missing.",
      },
      {
        id: "t4",
        title: "Additional documents requested",
        timestamp: "2025-02-03 12:15",
        status: "info",
        detail: "Query sent to hospital for missing docs.",
      },
      {
        id: "t5",
        title: "P2P scheduled",
        timestamp: "2025-02-03 16:20",
        status: "pending",
        detail: "Peer-to-peer call set for 2025-02-05 11:00.",
      },
      {
        id: "t6",
        title: "Current status",
        timestamp: "2025-02-03 16:30",
        status: "current",
        detail: "Awaiting hospital response to documentation query.",
      },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums current." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Orthopedic sub-limit ₹5L." },
      { id: "e4", label: "Benefit limit", status: "warning", value: "₹5L ortho sub-limit", detail: "Est. ₹4.2L; need itemized implant cost to confirm." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "Pre-existing OA; 2-year waiting period completed." },
    ],
    coding: {
      icd10: [
        { id: "icd1", type: "icd10", code: "M17.11", description: "Unilateral primary osteoarthritis, right knee", status: "valid" },
      ],
      cpt: [
        { id: "cpt1", type: "cpt", code: "27447", description: "Total knee arthroplasty with prosthesis", status: "valid" },
      ],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Joint replacement covered for severe OA.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer ortho policy", finding: "TKR covered for OA Stage III/IV (Kellgren-Lawrence). X-ray/MRI required for severity confirmation.", status: "conditional" },
    ],
    medicalNecessityScore: 71,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "M17.11",
        diagnosisDescription: "Unilateral primary osteoarthritis, right knee",
        procedureCode: "27447",
        procedureDescription: "Total knee arthroplasty with prosthesis",
        irdaApproved: true,
        policyApproved: false,
        aiSimilarityPct: 63,
        aiSummary: "Similar OA cases are approved when imaging confirms stage III/IV and conservative care failure is documented.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK507884/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "medium", description: "Cost breakdown incomplete; implant cost not itemized (IRDAI requirement)." },
      { id: "f2", category: "provider", severity: "medium", description: "Implant pricing 2.3x peer median; vendor repeats across unrelated cases." },
    ],
    queries: [
      { id: "q1", question: "Please provide (1) Itemized implant cost breakup (2) Doctor recommendation with hospital stamp (3) Pre-operative X-ray/MRI showing Kellgren-Lawrence stage.", status: "open", dueDate: "2025-02-06" },
    ],
    p2pRequired: true,
    p2pSummary: { scheduled: "2025-02-05 11:00", outcome: "Pending", reviewer: "Dr. S. Rao, Ortho (Insurer)" },
  },
  PA004: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "Pending", present: false },
        { label: "Policy document", value: "CARE/HL/2024/345678", present: false },
        { label: "Doctor consultation notes", value: "Senile cataract, bilateral", present: false },
        { label: "Provisional diagnosis (ICD-10)", value: "H25.1 – Senile cataract", present: false },
        { label: "Proposed treatment", value: "Phaco with IOL", present: false },
        { label: "Estimated cost", value: "₹1,95,000", present: false },
        { label: "Slit-lamp, A-scan", value: "Pending", present: false },
        { label: "Past illness", value: "Pending", present: false },
      ],
    },
    timeline: [
      {
        id: "t1",
        title: "Case received",
        timestamp: "2025-02-04 10:05",
        status: "done",
        detail: "Planned day-care request submitted.",
      },
      {
        id: "t2",
        title: "Assigned to reviewer",
        timestamp: "2025-02-04 10:22",
        status: "done",
        meta: [{ label: "Assignee", value: "Zoya Ali · Day-care Desk" }],
      },
      {
        id: "t3",
        title: "Documents missing",
        timestamp: "2025-02-04 10:40",
        status: "done",
        detail: "ID proof, policy, consent, and pre-op reports not received.",
      },
      {
        id: "t4",
        title: "Additional documents requested",
        timestamp: "2025-02-04 10:55",
        status: "info",
        detail: "Form A + consent + policy + pre-op reports requested.",
      },
      {
        id: "t5",
        title: "Hospital responded",
        timestamp: "2025-02-04 17:20",
        status: "done",
        detail: "Partial docs uploaded; ID proof still pending.",
      },
      {
        id: "t6",
        title: "Current status",
        timestamp: "2025-02-04 17:30",
        status: "current",
        detail: "Awaiting remaining ID proof for completion.",
      },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "New policy; premiums paid." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Valid." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Cataract under day-care." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "Within limit", detail: "Day-care sub-limit applicable." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "30-day waiting period completed." },
    ],
    coding: {
      icd10: [
        { id: "icd1", type: "icd10", code: "H25.1", description: "Senile nuclear cataract", status: "valid" },
      ],
      cpt: [
        { id: "cpt1", type: "cpt", code: "66984", description: "Extracapsular cataract removal with IOL", status: "valid" },
      ],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Cataract surgery standard; day-care eligible.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer policy", finding: "Phaco + IOL covered; documentation pending.", status: "conditional" },
    ],
    medicalNecessityScore: 76,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "H25.1",
        diagnosisDescription: "Senile nuclear cataract",
        procedureCode: "66984",
        procedureDescription: "Extracapsular cataract removal with IOL",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 74,
        aiSummary: "Most cataract IOL cases are approved after consent and pre-op tests are received.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK558907/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "none", description: "Awaiting documents." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital." },
    ],
    queries: [
      { id: "q1", question: "Complete document set not received. Please upload Form A, consent, policy, ID proof, and pre-op reports (slit-lamp, A-scan).", status: "open", dueDate: "2025-02-08" },
    ],
    p2pRequired: false,
  },
  PA005: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-2194", present: true },
        { label: "Policy document", value: "NIVA/HL/2023/889901", present: true },
        { label: "Doctor consultation notes", value: "Chronic sinusitis with polyps; failed meds", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "J33.9 – Nasal polyps", present: true },
        { label: "Proposed treatment", value: "Endoscopic sinus surgery", present: true },
        { label: "Estimated cost", value: "₹3,20,000", present: true },
        { label: "CT PNS", value: "Attached", present: true },
        { label: "Past illness records", value: "Allergic rhinitis history", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-02 08:18", status: "done", detail: "Planned pre-auth request submitted." },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-02 08:30", status: "done", meta: [{ label: "Assignee", value: "Anita Desai · Senior Claims Analyst" }] },
      { id: "t3", title: "Documentation complete", timestamp: "2025-02-02 08:50", status: "done", detail: "All checklist items verified." },
      { id: "t4", title: "Eligibility confirmed", timestamp: "2025-02-02 09:05", status: "done", detail: "Coverage and limits satisfied." },
      { id: "t5", title: "Current status", timestamp: "2025-02-02 09:12", status: "current", detail: "Under review for final decision." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums paid; no lapse." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid through Dec 2025." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "ENT surgery covered under plan." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹8L annual", detail: "₹3.2L within limit." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "2-year waiting period completed." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "J33.9", description: "Nasal polyp, unspecified", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "31254", description: "Nasal/sinus endoscopy, surgical; ethmoidectomy", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "ESS covered for refractory chronic sinusitis with polyps.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer ENT policy", finding: "CT PNS and symptom duration documented.", status: "met" },
    ],
    medicalNecessityScore: 86,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "J33.9",
        diagnosisDescription: "Nasal polyp, unspecified",
        procedureCode: "31254",
        procedureDescription: "Endoscopic ethmoidectomy",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 79,
        aiSummary: "ESS commonly approved when CT and failed medical therapy are documented.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK547685/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "none", description: "Complete documentation." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital." },
    ],
    queries: [],
    p2pRequired: false,
  },
  PA006: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-6043", present: true },
        { label: "Policy document", value: "HDFC/HL/2023/556677", present: true },
        { label: "Doctor consultation notes", value: "BPH with LUTS; recurrent retention", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "N40.1 – BPH with LUTS", present: true },
        { label: "Proposed treatment", value: "TURP", present: true },
        { label: "Estimated cost", value: "₹1,50,000", present: true },
        { label: "PSA report", value: "Pending", present: false },
        { label: "Uroflowmetry / PVR", value: "Pending", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-02 12:42", status: "done", detail: "Planned urology pre-auth submitted." },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-02 12:55", status: "done", meta: [{ label: "Assignee", value: "Kavitha Krishnan · Medical Review Specialist" }] },
      { id: "t3", title: "Documents missing", timestamp: "2025-02-02 13:10", status: "done", detail: "PSA + uroflowmetry reports not received." },
      { id: "t4", title: "Additional documents requested", timestamp: "2025-02-02 13:20", status: "info", detail: "PSA and uroflowmetry/PVR requested." },
      { id: "t5", title: "Current status", timestamp: "2025-02-02 13:30", status: "current", detail: "Awaiting missing investigations." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums current." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Urology procedures covered." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹6L annual", detail: "₹1.5L within limit." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "30-day waiting period completed." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "N40.1", description: "Benign prostatic hyperplasia with LUTS", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "52601", description: "Transurethral resection of prostate", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "TURP covered for symptomatic BPH.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer urology policy", finding: "PSA and uroflowmetry required for severity assessment.", status: "conditional" },
    ],
    medicalNecessityScore: 64,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "N40.1",
        diagnosisDescription: "BPH with LUTS",
        procedureCode: "52601",
        procedureDescription: "TURP",
        irdaApproved: true,
        policyApproved: false,
        aiSimilarityPct: 61,
        aiSummary: "Approvals typically require PSA and uroflowmetry to confirm severity.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK551704/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "low", description: "Missing investigations; request pending." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital." },
    ],
    queries: [
      { id: "q1", question: "Please upload PSA (last 3 months) and uroflowmetry/PVR reports for BPH severity assessment.", status: "open", dueDate: "2025-02-06" },
    ],
    p2pRequired: false,
  },
  PA007: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-9136", present: true },
        { label: "Policy document", value: "STAR/HL/2024/333444", present: true },
        { label: "Doctor consultation notes", value: "Left breast CA; surgical plan", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "C50.9 – Breast cancer", present: true },
        { label: "Proposed treatment", value: "Mastectomy + reconstruction", present: true },
        { label: "Estimated cost", value: "₹6,20,000", present: true },
        { label: "Histopathology report", value: "Pending", present: false },
        { label: "Oncology board notes", value: "Pending", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-03 09:12", status: "done", detail: "Onco-surgery pre-auth submitted." },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-03 09:28", status: "done", meta: [{ label: "Assignee", value: "Unassigned" }] },
      { id: "t3", title: "Documentation gaps detected", timestamp: "2025-02-03 09:45", status: "done", detail: "Histopathology + MDT notes missing." },
      { id: "t4", title: "Additional documents requested", timestamp: "2025-02-03 10:00", status: "info", detail: "Requested histopathology and oncology board notes." },
      { id: "t5", title: "Current status", timestamp: "2025-02-03 10:10", status: "current", detail: "Awaiting missing oncology documents." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums current." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Cancer surgery covered under plan." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹15L annual", detail: "₹6.2L within limit." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "Cancer waiting period satisfied." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "C50.9", description: "Malignant neoplasm of breast, unspecified", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "19303", description: "Mastectomy, simple, complete", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Cancer surgery covered with confirmed histopathology.", status: "conditional" },
      { id: "mn2", level: 2, source: "Insurer oncology policy", finding: "MDT board recommendation required.", status: "conditional" },
    ],
    medicalNecessityScore: 58,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "C50.9",
        diagnosisDescription: "Breast cancer",
        procedureCode: "19303",
        procedureDescription: "Mastectomy",
        irdaApproved: true,
        policyApproved: false,
        aiSimilarityPct: 55,
        aiSummary: "Approvals typically require histopathology and MDT board recommendation.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK553091/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "medium", description: "Histopathology missing." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital." },
    ],
    queries: [
      { id: "q1", question: "Please provide histopathology report and MDT oncology board notes.", status: "open", dueDate: "2025-02-06" },
    ],
    p2pRequired: true,
    p2pSummary: { scheduled: "2025-02-05 15:30", outcome: "Pending", reviewer: "Dr. N. Sethi, Onco (Insurer)" },
  },
  PA008: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-3372", present: true },
        { label: "Policy document", value: "ICICI/HL/2023/990011", present: true },
        { label: "Doctor consultation notes", value: "Right ureteric stone with colic", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "N20.1 – Ureteric calculus", present: true },
        { label: "Proposed treatment", value: "URS + laser lithotripsy", present: true },
        { label: "Estimated cost", value: "₹98,000", present: true },
        { label: "USG KUB", value: "Attached", present: true },
        { label: "RFT", value: "Attached", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-03 14:52", status: "done", detail: "Planned urology request submitted." },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-03 15:05", status: "done", meta: [{ label: "Assignee", value: "Rahul Mehta · Claims Analyst" }] },
      { id: "t3", title: "Documentation complete", timestamp: "2025-02-03 15:20", status: "done", detail: "All docs verified." },
      { id: "t4", title: "Eligibility confirmed", timestamp: "2025-02-03 15:35", status: "done", detail: "Coverage and waiting period satisfied." },
      { id: "t5", title: "Current status", timestamp: "2025-02-03 15:40", status: "current", detail: "Under review for final decision." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums current." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Urology covered." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹7L annual", detail: "₹98k within limit." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "30-day waiting period completed." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "N20.1", description: "Calculus of ureter", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "52356", description: "Ureteroscopy with lithotripsy, including stent", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "URS covered for symptomatic ureteric stone.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer urology policy", finding: "Imaging evidence documented.", status: "met" },
    ],
    medicalNecessityScore: 90,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "N20.1",
        diagnosisDescription: "Ureteric calculus",
        procedureCode: "52356",
        procedureDescription: "Ureteroscopy with lithotripsy",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 83,
        aiSummary: "Approvals common with imaging evidence and acute symptoms.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK560674/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "none", description: "Complete documentation." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital." },
    ],
    queries: [],
    p2pRequired: false,
  },
  PA009: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-1408", present: true },
        { label: "Policy document", value: "CARE/HL/2024/225588", present: true },
        { label: "Doctor consultation notes", value: "CAD with triple vessel disease", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "I25.10 – CAD", present: true },
        { label: "Proposed treatment", value: "CABG (3 vessels)", present: true },
        { label: "Estimated cost", value: "₹4,10,000", present: true },
        { label: "2D Echo report", value: "Pending", present: false },
        { label: "Coronary angiography CD", value: "Pending", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-03 18:10", status: "done", detail: "Cardiac pre-auth submitted." },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-03 18:25", status: "done", meta: [{ label: "Assignee", value: "Anita Desai · Senior Claims Analyst" }] },
      { id: "t3", title: "Documents missing", timestamp: "2025-02-03 18:40", status: "done", detail: "Echo and angiography CD not received." },
      { id: "t4", title: "Additional documents requested", timestamp: "2025-02-03 18:50", status: "info", detail: "Requested echo + angiography CD." },
      { id: "t5", title: "Current status", timestamp: "2025-02-03 19:05", status: "current", detail: "Awaiting cardiac investigations." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums current." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Cardiac surgery covered under plan." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹12L cardiac sub-limit", detail: "₹4.1L within limit." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "Cardiac waiting period satisfied." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "I25.10", description: "Atherosclerotic heart disease", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "33533", description: "CABG, arterial graft", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "CABG covered for multivessel CAD with angiography evidence.", status: "conditional" },
      { id: "mn2", level: 2, source: "Insurer cardiac policy", finding: "Echo and angiography required.", status: "conditional" },
    ],
    medicalNecessityScore: 60,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "I25.10",
        diagnosisDescription: "CAD",
        procedureCode: "33533",
        procedureDescription: "CABG",
        irdaApproved: true,
        policyApproved: false,
        aiSimilarityPct: 57,
        aiSummary: "Approvals depend on echo + angiography documentation.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK507703/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "medium", description: "Key cardiac investigations missing." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital." },
    ],
    queries: [
      { id: "q1", question: "Please upload 2D Echo report and coronary angiography CD/report.", status: "open", dueDate: "2025-02-07" },
    ],
    p2pRequired: true,
    p2pSummary: { scheduled: "2025-02-06 10:30", outcome: "Pending", reviewer: "Dr. V. Iyer, Cardiology (Insurer)" },
  },
  PA010: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-7712", present: true },
        { label: "Policy document", value: "NIVA/HL/2023/114466", present: true },
        { label: "Doctor consultation notes", value: "Medial meniscus tear; failed PT", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "S83.241 – Medial meniscus tear", present: true },
        { label: "Proposed treatment", value: "Arthroscopic meniscectomy", present: true },
        { label: "Estimated cost", value: "₹86,000", present: true },
        { label: "MRI knee", value: "Attached", present: true },
        { label: "Past illness records", value: "Nil relevant", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-01 07:45", status: "done", detail: "Ortho day-care request submitted." },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-01 08:00", status: "done", meta: [{ label: "Assignee", value: "Kavitha Krishnan · Medical Review Specialist" }] },
      { id: "t3", title: "Documentation complete", timestamp: "2025-02-01 08:15", status: "done", detail: "MRI + consent verified." },
      { id: "t4", title: "Eligibility confirmed", timestamp: "2025-02-01 08:30", status: "done", detail: "Coverage and limits satisfied." },
      { id: "t5", title: "Decision issued", timestamp: "2025-02-01 09:05", status: "done", detail: "Pre-auth approved." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums current." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid." },
      { id: "e3", label: "Service coverage", status: "pass", value: "Covered", detail: "Ortho day-care covered." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹5L annual", detail: "₹86k within limit." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "30-day waiting period completed." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "S83.241", description: "Medial meniscus tear, right knee", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "29881", description: "Arthroscopy, knee; meniscectomy", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Arthroscopic meniscectomy covered with MRI evidence.", status: "met" },
      { id: "mn2", level: 2, source: "Insurer ortho policy", finding: "Failed conservative therapy documented.", status: "met" },
    ],
    medicalNecessityScore: 93,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "S83.241",
        diagnosisDescription: "Medial meniscus tear",
        procedureCode: "29881",
        procedureDescription: "Knee meniscectomy",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 85,
        aiSummary: "Approvals common with MRI-confirmed tear and failed PT.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK539884/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "none", description: "Complete documentation." },
      { id: "f2", category: "provider", severity: "none", description: "Network hospital." },
    ],
    queries: [],
    p2pRequired: false,
  },
  PA011: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-5529", present: true },
        { label: "Policy document", value: "HDFC/HL/2022/778899", present: true },
        { label: "Doctor consultation notes", value: "Morbid obesity; bariatric evaluation", present: true },
        { label: "Provisional diagnosis (ICD-10)", value: "E66.01 – Morbid obesity", present: true },
        { label: "Proposed treatment", value: "Sleeve gastrectomy", present: true },
        { label: "Estimated cost", value: "₹2,40,000", present: true },
        { label: "BMI assessment report", value: "Pending", present: false },
        { label: "Supervised weight loss records", value: "Pending", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-01-31 10:35", status: "done", detail: "Bariatric pre-auth submitted." },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-01-31 10:50", status: "done", meta: [{ label: "Assignee", value: "Rahul Mehta · Claims Analyst" }] },
      { id: "t3", title: "Documentation gaps detected", timestamp: "2025-01-31 11:05", status: "done", detail: "BMI assessment + weight-loss program missing." },
      { id: "t4", title: "Medical review", timestamp: "2025-01-31 11:40", status: "done", detail: "Eligibility criteria not met; documents missing." },
      { id: "t5", title: "Decision issued", timestamp: "2025-01-31 12:05", status: "done", detail: "Pre-auth rejected due to non-compliance." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums current." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Policy valid." },
      { id: "e3", label: "Service coverage", status: "warning", value: "Conditional", detail: "Bariatric surgery requires criteria compliance." },
      { id: "e4", label: "Benefit limit", status: "pass", value: "₹4L annual", detail: "₹2.4L within limit." },
      { id: "e5", label: "Waiting period", status: "pass", value: "Elapsed", detail: "Waiting period satisfied." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "E66.01", description: "Morbid obesity due to excess calories", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "43775", description: "Laparoscopic sleeve gastrectomy", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Bariatric surgery covered with BMI and supervised program evidence.", status: "not_met" },
      { id: "mn2", level: 2, source: "Insurer bariatric policy", finding: "Weight-loss program documentation missing.", status: "not_met" },
    ],
    medicalNecessityScore: 32,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "E66.01",
        diagnosisDescription: "Morbid obesity",
        procedureCode: "43775",
        procedureDescription: "Sleeve gastrectomy",
        irdaApproved: false,
        policyApproved: false,
        aiSimilarityPct: 41,
        aiSummary: "Approvals require BMI >40 (or >35 with comorbidities) and supervised program records.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK482428/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "high", description: "Core eligibility documentation missing." },
      { id: "f2", category: "patient", severity: "medium", description: "Prior bariatric requests show conflicting BMI history and reused records." },
    ],
    queries: [],
    p2pRequired: false,
  },
  PA012: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "Pending", present: false },
        { label: "Policy document", value: "STAR/HL/2024/661122", present: false },
        { label: "Doctor consultation notes", value: "Rectal bleeding; diagnostic colonoscopy", present: false },
        { label: "Provisional diagnosis (ICD-10)", value: "K62.5 – Rectal bleeding", present: false },
        { label: "Proposed treatment", value: "Colonoscopy with biopsy", present: false },
        { label: "Estimated cost", value: "₹52,000", present: false },
        { label: "Pre-op investigations", value: "Pending", present: false },
        { label: "Consent form", value: "Pending", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case drafted", timestamp: "2025-02-04 09:10", status: "done", detail: "Draft created by hospital desk." },
      { id: "t2", title: "Documents pending", timestamp: "2025-02-04 09:20", status: "info", detail: "Form A, consent, and ID proof not uploaded." },
      { id: "t3", title: "Current status", timestamp: "2025-02-04 09:25", status: "current", detail: "Awaiting submission." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "warning", value: "Unknown", detail: "Policy not attached." },
      { id: "e2", label: "Coverage dates", status: "warning", value: "Unknown", detail: "Policy validity not verified." },
      { id: "e3", label: "Service coverage", status: "warning", value: "Unknown", detail: "Coverage pending document review." },
      { id: "e4", label: "Benefit limit", status: "warning", value: "Unknown", detail: "Policy limit not verified." },
      { id: "e5", label: "Waiting period", status: "warning", value: "Unknown", detail: "Waiting period not verified." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "K62.5", description: "Hemorrhage of anus and rectum", status: "missing_specificity" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "45380", description: "Colonoscopy with biopsy", status: "missing_specificity" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Diagnostic colonoscopy covered with clinical notes.", status: "conditional" },
    ],
    medicalNecessityScore: 22,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "K62.5",
        diagnosisDescription: "Rectal bleeding",
        procedureCode: "45380",
        procedureDescription: "Colonoscopy with biopsy",
        irdaApproved: true,
        policyApproved: false,
        aiSimilarityPct: 39,
        aiSummary: "Approvals need clinical notes, consent, and policy verification.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK470551/",
        sourceLabel: "View guidance",
      },
    ],
    fraudFlags: [
      { id: "f1", category: "document", severity: "low", description: "Draft with missing documents." },
    ],
    queries: [
      { id: "q1", question: "Please upload Form A, consent, policy copy/e-card, ID proof, and pre-op investigations.", status: "open", dueDate: "2025-02-07" },
    ],
    p2pRequired: false,
  },
  PA013: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID (Aadhaar)", value: "XXXX-XXXX-1122", present: true },
        { label: "Policy document", value: "ICICI/HL/2023/123321", present: true },
        { label: "Doctor notes", value: "Menorrhagia, multiple large fibroids", present: true },
        { label: "Provisional diagnosis", value: "D25.9 – Leiomyoma of uterus", present: true },
        { label: "Proposed treatment", value: "Total abdominal hysterectomy", present: true },
        { label: "Estimated cost", value: "₹3,15,000", present: true },
        { label: "USG Abdomen/Pelvis", value: "Fibroids 8cm, 6cm detected", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-04 10:15", status: "done" },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-04 10:30", status: "done", meta: [{ label: "Assignee", value: "Anita Desai" }] },
      { id: "t3", title: "Current status", timestamp: "2025-02-04 11:00", status: "current", detail: "Under review for medical necessity." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Premiums paid." },
      { id: "e2", label: "Coverage dates", status: "pass", value: "Within validity", detail: "Valid." },
      { id: "e3", label: "Benefit limit", status: "pass", value: "₹15L annual", detail: "Within limit." },
      { id: "e4", label: "Waiting period", status: "pass", value: "Elapsed", detail: "2-year period for fibroids completed." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "D25.9", description: "Leiomyoma of uterus, unspecified", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "58150", description: "Total abdominal hysterectomy", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "IRDAI Guidelines", finding: "Hysterectomy covered for symptomatic fibroids.", status: "met" },
      { id: "mn2", level: 2, source: "Clinical notes", finding: "Failed conservative management documented.", status: "met" },
    ],
    medicalNecessityScore: 89,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "D25.9",
        diagnosisDescription: "Uterine fibroids",
        procedureCode: "58150",
        procedureDescription: "Hysterectomy",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 82,
        aiSummary: "High approval rate for fibroids >5cm with menorrhagia symptoms.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK546682/",
        sourceLabel: "Evidence",
      },
    ],
    fraudFlags: [{ id: "f1", category: "document", severity: "none", description: "Consistent documentation." }],
    queries: [],
    p2pRequired: false,
  },
  PA014: {
    requestSummary: {
      admissionType: "emergency",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "XXXX-XXXX-3344", present: true },
        { label: "Trauma summary", value: "RTA, severe pain left thigh", present: true },
        { label: "Provisional diagnosis", value: "S72.30 – Fracture shaft of femur", present: true },
        { label: "Proposed treatment", value: "ORIF with intramedullary nail", present: true },
        { label: "Estimated cost", value: "₹1,20,000", present: true },
        { label: "X-ray Femur", value: "Not received", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received (ER)", timestamp: "2025-02-04 11:45", status: "done" },
      { id: "t2", title: "Query sent", timestamp: "2025-02-04 12:15", status: "info", detail: "X-ray report requested." },
      { id: "t3", title: "Current status", timestamp: "2025-02-04 12:30", status: "current", detail: "Awaiting X-ray report." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active", detail: "Group insurance." },
      { id: "e2", label: "Waiting period", status: "pass", value: "Waived", detail: "Accidental injury; 30-day waiver applies." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "S72.30", description: "Fracture of shaft of femur", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "27506", description: "ORIF femur shaft fracture", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "Trauma protocol", finding: "Immediate surgical fixation required for femur fracture.", status: "met" },
    ],
    medicalNecessityScore: 78,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "S72.30",
        diagnosisDescription: "Femur fracture",
        procedureCode: "27506",
        procedureDescription: "ORIF",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 88,
        aiSummary: "Emergency ORIF for long bone fractures is standard of care.",
        sourceUrl: "https://www.ncbi.nlm.nih.gov/books/NBK459228/",
        sourceLabel: "Evidence",
      },
    ],
    fraudFlags: [{ id: "f1", category: "provider", severity: "none", description: "Network hospital." }],
    queries: [{ id: "q1", question: "Please upload X-ray report of left femur.", status: "open", dueDate: "2025-02-05" }],
    p2pRequired: false,
  },
  PA015: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "XXXX-XXXX-9988", present: true },
        { label: "Oncology notes", value: "Chemotherapy Cycle #3", present: true },
        { label: "Diagnosis", value: "C34.9 – Lung Cancer", present: true },
        { label: "Proposed treatment", value: "Injection Pemetrexed + Carboplatin", present: true },
        { label: "Estimated cost", value: "₹65,000", present: true },
        { label: "Biopsy report", value: "Not attached", present: false },
        { label: "PET Scan", value: "Not attached", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-04 13:20", status: "done" },
      { id: "t2", title: "Documentation check", timestamp: "2025-02-04 13:45", status: "done", detail: "Missing core oncology docs." },
      { id: "t3", title: "Current status", timestamp: "2025-02-04 14:00", status: "current", detail: "Awaiting documents." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active" },
      { id: "e2", label: "Benefit limit", status: "pass", value: "₹8L annual" },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "C34.9", description: "Malignant neoplasm of lung", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "96413", description: "Chemotherapy administration, IV infusion", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "Oncology Guidelines", finding: "Pemetrexed + Carboplatin is standard for non-squamous NSCLC.", status: "met" },
      { id: "mn2", level: 2, source: "Documentation", finding: "Missing staging and biopsy confirmation.", status: "not_met" },
    ],
    medicalNecessityScore: 42,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "C34.9",
        diagnosisDescription: "Lung Cancer",
        procedureCode: "96413",
        procedureDescription: "Chemotherapy",
        irdaApproved: true,
        policyApproved: false,
        aiSimilarityPct: 45,
        aiSummary: "Oncology claims require biopsy and staging for the first few cycles.",
        sourceUrl: "https://www.nccn.org/guidelines/",
        sourceLabel: "Evidence",
      },
    ],
    fraudFlags: [{ id: "f1", category: "document", severity: "high", description: "Core medical reports missing for expensive treatment." }],
    queries: [{ id: "q1", question: "Please provide histopathology report and staging PET scan.", status: "open", dueDate: "2025-02-07" }],
    p2pRequired: false,
  },
  PA016: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "XXXX-XXXX-7766", present: true },
        { label: "Policy document", value: "STAR/HL/2024/776655", present: true },
        { label: "Cardiology notes", value: "Severe symptomatic aortic stenosis", present: true },
        { label: "Diagnosis", value: "I35.0 – Nonrheumatic aortic stenosis", present: true },
        { label: "Proposed treatment", value: "Surgical aortic valve replacement", present: true },
        { label: "Estimated cost", value: "₹7,50,000", present: true },
        { label: "Echo report", value: "AVA 0.7 cm2, gradient 45 mmHg", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-04 15:10", status: "done" },
      { id: "t2", title: "Assigned to reviewer", timestamp: "2025-02-04 15:25", status: "done", meta: [{ label: "Assignee", value: "Kavitha Krishnan" }] },
      { id: "t3", title: "Current status", timestamp: "2025-02-04 15:40", status: "current", detail: "Medical review ongoing." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active" },
      { id: "e2", label: "Benefit limit", status: "pass", value: "₹20L annual" },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "I35.0", description: "Nonrheumatic aortic stenosis", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "33405", description: "Aortic valve replacement", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "Cardiac guidelines", finding: "AVR indicated for symptomatic severe AS.", status: "met" },
    ],
    medicalNecessityScore: 92,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "I35.0",
        diagnosisDescription: "Aortic stenosis",
        procedureCode: "33405",
        procedureDescription: "Valve replacement",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 85,
        aiSummary: "Confirmed severe AS (AVA < 1cm2) with symptoms has high approval rates.",
        sourceUrl: "https://www.acc.org/guidelines",
        sourceLabel: "Evidence",
      },
    ],
    fraudFlags: [{ id: "f1", category: "document", severity: "none", description: "Documents verified." }],
    queries: [],
    p2pRequired: false,
  },
  PA017: {
    requestSummary: {
      admissionType: "emergency",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "XXXX-XXXX-1122", present: true },
        { label: "Clinical notes", value: "High grade fever, myalgia, rash", present: true },
        { label: "Diagnosis", value: "A91 – Dengue hemorrhagic fever", present: true },
        { label: "Proposed treatment", value: "IV fluids, platelet monitoring", present: true },
        { label: "Estimated cost", value: "₹42,000", present: true },
        { label: "NS1 Antigen", value: "Not attached", present: false },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received (ER)", timestamp: "2025-02-04 16:30", status: "done" },
      { id: "t2", title: "Query sent", timestamp: "2025-02-04 16:50", status: "info", detail: "Lab reports requested." },
      { id: "t3", title: "Current status", timestamp: "2025-02-04 17:00", status: "current", detail: "Awaiting Lab reports." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active" },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "A91", description: "Dengue hemorrhagic fever", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "99222", description: "Initial hospital care", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "Medicine guidelines", finding: "Inpatient care for Dengue with warning signs.", status: "conditional" },
    ],
    medicalNecessityScore: 35,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "A91",
        diagnosisDescription: "Dengue",
        procedureCode: "99222",
        procedureDescription: "Inpatient care",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 65,
        aiSummary: "Lab confirmation of Dengue is strictly required for reimbursement/cashless.",
        sourceUrl: "https://www.who.int/news-room/fact-sheets/detail/dengue-and-severe-dengue",
        sourceLabel: "Evidence",
      },
    ],
    fraudFlags: [{ id: "f1", category: "document", severity: "medium", description: "Lab report missing for fever management." }],
    queries: [{ id: "q1", question: "Please upload NS1/IgM positive report and serial platelet counts.", status: "open", dueDate: "2025-02-06" }],
    p2pRequired: false,
  },
  PA018: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "XXXX-XXXX-5544", present: true },
        { label: "Clinical notes", value: "Ventral hernia, reducible", present: true },
        { label: "Diagnosis", value: "K43.9 – Ventral hernia", present: true },
        { label: "Proposed treatment", value: "Laparoscopic IPOM", present: true },
        { label: "Estimated cost", value: "₹1,85,000", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case drafted", timestamp: "2025-02-04 17:20", status: "done" },
      { id: "t2", title: "Current status", timestamp: "2025-02-04 17:30", status: "current", detail: "Awaiting hospital submission." },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active" },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "K43.9", description: "Ventral hernia without obstruction", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "49652", description: "Laparoscopic ventral hernia repair", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "Surgical guidelines", finding: "IPOM indicated for symptomatic ventral hernia.", status: "met" },
    ],
    medicalNecessityScore: 10,
    medicalNecessityInsights: [],
    fraudFlags: [],
    queries: [],
    p2pRequired: false,
  },
  PA019: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "XXXX-XXXX-9136", present: true },
        { label: "Nephrology notes", value: "Stage V CKD, planning for HD", present: true },
        { label: "Diagnosis", value: "N18.5 – CKD Stage V", present: true },
        { label: "Proposed treatment", value: "AV Fistula creation", present: true },
        { label: "Estimated cost", value: "₹55,000", present: true },
        { label: "Creatinine", value: "8.2 mg/dL", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-01 09:00", status: "done" },
      { id: "t2", title: "Documentation verified", timestamp: "2025-02-01 09:20", status: "done" },
      { id: "t3", title: "Approved", timestamp: "2025-02-01 10:15", status: "done" },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active" },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "N18.5", description: "Chronic kidney disease, stage 5", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "36821", description: "AV fistula creation, direct anastomosis", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "Nephrology guidelines", finding: "AV fistula creation indicated for CKD Stage V.", status: "met" },
    ],
    medicalNecessityScore: 95,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "N18.5",
        diagnosisDescription: "CKD Stage 5",
        procedureCode: "36821",
        procedureDescription: "AV Fistula",
        irdaApproved: true,
        policyApproved: true,
        aiSimilarityPct: 94,
        aiSummary: "Fistula creation for Stage 5 CKD is standard preventative care for dialysis.",
        sourceUrl: "https://www.kidney.org/professionals/KDOQI/guidelines",
        sourceLabel: "Evidence",
      },
    ],
    fraudFlags: [],
    queries: [],
    p2pRequired: false,
  },
  PA020: {
    requestSummary: {
      admissionType: "planned",
      submittedWithinSLA: true,
      items: [
        { label: "Patient ID", value: "XXXX-XXXX-7712", present: true },
        { label: "Clinical notes", value: "Severe toothache, dental caries", present: true },
        { label: "Diagnosis", value: "K02.9 – Dental caries, unspecified", present: true },
        { label: "Proposed treatment", value: "RCT with PFM Crown", present: true },
        { label: "Estimated cost", value: "₹1,25,000", present: true },
      ],
    },
    timeline: [
      { id: "t1", title: "Case received", timestamp: "2025-02-02 14:00", status: "done" },
      { id: "t2", title: "Eligibility check", timestamp: "2025-02-02 14:30", status: "done", detail: "Dental exclusion identified." },
      { id: "t3", title: "Rejected", timestamp: "2025-02-02 15:00", status: "done" },
    ],
    eligibility: [
      { id: "e1", label: "Policy status", status: "pass", value: "Active" },
      { id: "e2", label: "Dental coverage", status: "fail", value: "Excluded", detail: "Policy exclusion clause G.4.2 applies." },
    ],
    coding: {
      icd10: [{ id: "icd1", type: "icd10", code: "K02.9", description: "Dental caries, unspecified", status: "valid" }],
      cpt: [{ id: "cpt1", type: "cpt", code: "D3330", description: "Root canal therapy; molar", status: "valid" }],
    },
    medicalNecessity: [
      { id: "mn1", level: 1, source: "Dental guidelines", finding: "RCT indicated for pulpitis due to caries.", status: "met" },
    ],
    medicalNecessityScore: 50,
    medicalNecessityInsights: [
      {
        id: "mni1",
        diagnosisCode: "K02.9",
        diagnosisDescription: "Dental caries",
        procedureCode: "D3330",
        procedureDescription: "Root canal",
        irdaApproved: false,
        policyApproved: false,
        aiSimilarityPct: 20,
        aiSummary: "Dental procedures are standard exclusions in basic health policies unless trauma-related.",
        sourceUrl: "https://www.irdai.gov.in/",
        sourceLabel: "Regulation",
      },
    ],
    fraudFlags: [],
    queries: [],
    p2pRequired: false,
  },
};

export function getWorkflowData(preAuthId: string): PreAuthWorkflowData | null {
  return workflowByPreAuthId[preAuthId] ?? null;
}

export const WORKFLOW_STAGES: { id: WorkflowStageId; title: string; shortTitle: string; description: string }[] = [
  { id: "documentation", shortTitle: "Docs", title: "Documentation & Eligibility", description: "Verify completeness, review documents, and check eligibility." },
  { id: "medical_coding", shortTitle: "Coding", title: "Medical Coding Accuracy", description: "ICD-10 and CPT validation." },
  { id: "medical_necessity", shortTitle: "Necessity", title: "Medical Necessity", description: "IRDAI → insurer policy → clinical criteria." },
  { id: "fraud_anomaly", shortTitle: "Fraud", title: "Fraud & Anomaly", description: "Red flags and pattern checks." },
  { id: "queries_and_decision", shortTitle: "Queries & Decision", title: "Queries & Decision", description: "Open queries and final decision: Approve, Deny, Query, or Conditional." },
];
